.PHONY: all

all: test-falloc-trunc test-falloc-seek

test-falloc-trunc: test-falloc-trunc.c
	cc -o test-falloc-trunc -Wall -Wextra -g test-falloc-trunc.c

test-falloc-seek: test-falloc-seek.c
	cc -o test-falloc-seek -Wall -Wextra -g test-falloc-seek.c
