name: run-posix-tests
run-name: Run various POSIX programs on different platforms
on:
  workflow_dispatch:
jobs:
  inet-pnp:
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    name: Run inet-pnp on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd writeups/inet-pnp
          make test

  eyeball:
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    name: Run eyeball on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd writeups/ipv6/eyeball
          make test
